import com.github.jengelman.gradle.plugins.shadow.tasks.ShadowJar

plugins {
    id 'java-library'
    id 'idea'
    id 'eclipse'
    id 'maven-publish'
    alias libs.plugins.licenser
    alias libs.plugins.gradleutils
    id 'net.minecraftforge.gitversion'
    id 'net.minecraftforge.changelog'
    alias libs.plugins.shadow
}

gradleutils.displayName = 'Git Version'
final projectVendor = 'Forge Development LLC'
description = 'Used by MinecraftForge projects to calculate project versions based on Git history.'
base.archivesName = 'gitversion'
group = 'net.minecraftforge'
version = gitversion.version

java {
    toolchain.languageVersion = JavaLanguageVersion.of(17)
    withSourcesJar()
}

configurations {
	register('cli') {
	    extendsFrom implementation
	}
}

dependencies {
    // Static Analysis
    api libs.annotations.jspecify
    compileOnly libs.annotations.jetbrains

    // Git
    implementation libs.jgit

    // Config
    implementation libs.toml

    // JSON Output
    implementation libs.gson

    cli projects.gitversionCli
}

license {
    header = file 'LICENSE-header.txt'
    newLine = false
    exclude '**/*.properties'
}

tasks.named('jar', Jar) {
    manifest {
        attributes([
            'Specification-Title'   : gradleutils.displayName,
            'Specification-Vendor'  : projectVendor,
            'Specification-Version' : gitversion.info.get().tag,
            'Implementation-Title'  : gradleutils.displayName,
            'Implementation-Vendor' : projectVendor,
            'Implementation-Version': project.version
        ], 'net/minecraftforge/gitver/api/')
    }
}

tasks.named('shadowJar', ShadowJar) {
    manifest {
        attributes([
            'Main-Class': 'net.minecraftforge.gitver.cli.Main'
        ])
    }

    archiveClassifier = 'fatjar'

    configurations = project.configurations.named('cli').map { [it] }

    enableAutoRelocation = true
    relocationPrefix = 'net.minecraftforge.gitver.shadow'
    relocate('net.minecraftforge.gitver', 'net.minecraftforge.gitver')
    // Rewrite JOpt's message files, so that help text is displayed nicely.
    transform(com.github.jengelman.gradle.plugins.shadow.transformers.PropertiesFileTransformer) {
        paths = [ 'Messages.properties$' ]
        keyTransformer = { key -> 'net.minecraftforge.gitver.shadow.' + key }
    }
    transform(com.github.jengelman.gradle.plugins.shadow.transformers.Log4j2PluginsCacheFileTransformer)
    transform(com.github.jengelman.gradle.plugins.shadow.transformers.ServiceFileTransformer)

    minimize {
        exclude(project(':gitversion-cli'))
    }

    exclude('OSGI-INF/**')
    exclude('META-INF/maven/**')
    exclude('META-INF/proguard/**')
}

changelog {
    fromBase()
}

publishing {
    repositories {
        maven gradleutils.publishingForgeMaven
    }

    publications.register('mavenJava', MavenPublication) {
        from components.java

        changelog.publish(it)
        gradleutils.promote(it)

        pom { pom ->
            name = gradleutils.displayName
            description = project.description

            gradleutils.pom.addRemoteDetails(pom)

            licenses {
                license gradleutils.pom.licenses.LGPLv2_1
            }

            developers {
                developer gradleutils.pom.developers.Jonathing
            }
        }
    }
}
