plugins {
	id 'application'
    id 'net.minecraftforge.gitversion'
}

group = 'net.minecraftforge'
version = gitversion.of(rootProject).version

java {
    toolchain.languageVersion = JavaLanguageVersion.of(17)
    withSourcesJar()
}

application {
    mainClass = 'net.minecraftforge.gitver.cli.Main'
}

dependencies {
    implementation projects.gitversion
    implementation libs.jopt
    runtimeOnly libs.slf4j
}