plugins {
	id 'application'
}

group = 'net.minecraftforge'
version = gitversion.tagOffset

java {
    toolchain.languageVersion = JavaLanguageVersion.of(17)
    withSourcesJar()
}

application {
    mainClass = 'net.minecraftforge.gitver.cli.Main'
}

dependencies {
    implementation rootProject
    implementation libs.jopt
    runtimeOnly libs.slf4j
}