name: Publish Plugin - GitVersion

on:
  push:
    branches: [ 'master' ]
    paths:
      - 'gitversion-gradle/**'
      - '!gitversion-gradle/changelog-gradle/**'
      - '!.github/workflows/**'
      - '!docs/**'
      - '!README.md'

permissions:
  contents: read

jobs:
  build:
    uses: MinecraftForge/SharedActions/.github/workflows/gradle.yml@v0
    with:
      java: 17
      gradle_tasks: ':gitversion-gradle:check :gitversion-gradle:publish :gitversion-gradle:publishPlugins'
      project_path: 'gitversion-gradle'
    secrets:
      DISCORD_WEBHOOK: ${{ secrets.DISCORD_WEBHOOK }}
      MAVEN_USER: ${{ secrets.MAVEN_USER }}
      MAVEN_PASSWORD: ${{ secrets.MAVEN_PASSWORD }}
      GRADLE_PUBLISH_KEY: ${{ secrets.GRADLE_PUBLISH_KEY }}
      GRADLE_PUBLISH_SECRET: ${{ secrets.GRADLE_PUBLISH_SECRET }}
